import PySimpleGUI as sg
# sg.theme_previewer()
theme_list = sg.theme_list()
print(theme_list)
theme_list = [
    'Black',
    'BlueMono',
    'BluePurple',
    'BrightColors',
    'BrownBlue',
    'Dark',
    [
        'Dark',
        [
            [
                'Dark',
                'Dark2'
            ],
            'DarkAmber',
            'DarkBlack',
            [
                'DarkBlack',
                'DarkBlack1'
            ],
            'DarkBlue',
            [
                'DarkBlue',
                'DarkBlue1',
                'DarkBlue2',
                'DarkBlue3',
                'DarkBlue4',
                'DarkBlue5',
                'DarkBlue6',
                'DarkBlue7',
                'DarkBlue8',
                'DarkBlue9',
                'DarkBlue10',
                'DarkBlue11',
                'DarkBlue12',
                'DarkBlue13',
                'DarkBlue14',
                'DarkBlue15',
                'DarkBlue16',
                'DarkBlue17'
            ],
            'DarkBrown',
            [
                'DarkBrown',
                'DarkBrown1',
                'DarkBrown2',
                'DarkBrown3',
                'DarkBrown4',
                'DarkBrown5',
                'DarkBrown6',
                'DarkBrown7'
            ],
            'DarkGreen',
            [
                'DarkGreen',
                'DarkGreen1',
                'DarkGreen2',
                'DarkGreen3',
                'DarkGreen4',
                'DarkGreen5',
                'DarkGreen6',
                'DarkGreen7'
            ],
            'DarkGrey',
            [
                'DarkGrey',
                'DarkGrey1',
                'DarkGrey2',
                'DarkGrey3',
                'DarkGrey4',
                'DarkGrey5',
                'DarkGrey6',
                'DarkGrey7',
                'DarkGrey8',
                'DarkGrey9',
                'DarkGrey10',
                'DarkGrey11',
                'DarkGrey12',
                'DarkGrey13',
                'DarkGrey14',
                'DarkGrey15'
            ],
            'DarkPurple',
            [
                'DarkPurple',
                'DarkPurple1',
                'DarkPurple2',
                'DarkPurple3',
                'DarkPurple4',
                'DarkPurple5',
                'DarkPurple6',
                'DarkPurple7'
            ],
            'DarkRed',
            [
                'DarkRed',
                'DarkRed1',
                'DarkRed2'
            ],
            'DarkTanBlue',
            'DarkTeal',
            [
                'DarkTeal',
                'DarkTeal1',
                'DarkTeal2',
                'DarkTeal3',
                'DarkTeal4',
                'DarkTeal5',
                'DarkTeal6',
                'DarkTeal7',
                'DarkTeal8',
                'DarkTeal9',
                'DarkTeal10',
                'DarkTeal11',
                'DarkTeal12'
            ]
        ]
    ],
    'Default',
    [
        'Default', 'Default1'
    ],
    'DefaultNoMoreNagging',
    'GrayGrayGray',
    'Green',
    [
        'Green',
        'GreenMono',
        'GreenTan'
    ],
    'HotDogStand',
    'Kayak',
    'Light',
    [
        'LightBlue',
        [
            'LightBlue',
            'LightBlue1',
            'LightBlue2',
            'LightBlue3',
            'LightBlue4',
            'LightBlue5',
            'LightBlue6',
            'LightBlue7'
        ],
        'LightBrown',
        [
            'LightBrown',
            'LightBrown1',
            'LightBrown2',
            'LightBrown3',
            'LightBrown4',
            'LightBrown5',
            'LightBrown6',
            'LightBrown7',
            'LightBrown8',
            'LightBrown9',
            'LightBrown10',
            'LightBrown11',
            'LightBrown12',
            'LightBrown13'
        ],
        'LightGreen',
        [
            'LightGreen',
            'LightGreen1',
            'LightGreen2',
            'LightGreen3',
            'LightGreen4',
            'LightGreen5',
            'LightGreen6',
            'LightGreen7',
            'LightGreen8',
            'LightGreen9',
            'LightGreen10'
        ],
        'LightGrey',
        [
            'LightGrey',
            'LightGray1',
            'LightGrey1',
            'LightGrey2',
            'LightGrey3',
            'LightGrey4',
            'LightGrey5',
            'LightGrey6'
        ],
        'LightPurple',
        'LightTeal',
        'LightYellow'
    ],
    'Material',
    [
        'Material1',
        'Material2'
    ],
    'NeutralBlue',
    'Purple',
    'Python',
    'PythonPlus',
    'Reddit',
    'Reds',
    'SandyBeach',
    'SystemDefault',
    [
        'SystemDefault',
        'SystemDefault1',
        'SystemDefaultForReal'
    ],
    'Tan',
    'TanBlue',
    'TealMono',
    'Topanga'
]
